name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "latest"
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from package.json
        id: extract_version
        run: |
          echo "::set-output name=version::$(jq -r .version package.json)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/atomix-to-notion:latest
            ${{ secrets.DOCKER_USERNAME }}/atomix-to-notion:${{ steps.extract_version.outputs.version }}
